services:
  web:
    build: ./frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/usr/src/app
      - ./.next:/usr/src/app/.next
    environment:
      NODE_OPTIONS: "--max-old-space-size=2000"


  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web



  